### ISSUE TITLE
Conflict with other map elements

### ISSUE THREAD

**Issue by sprattek** [smithmicro/mapbox-gl-circle#61]
Hey guys,

I've noticed that there is an issue while moving with circle while there are also some other elements placed on the map, like markers. When you move across these elements it will stop dragging the circle, I've prepared codepen example so you can check it out. I think that issue exists there from version 1.4.0, I'm using version 1.3.0 for now as it's working fine there.

[Example](https://codepen.io/anon/pen/vWxLXw)

**Comment by carlba** [comment]
This issue should be fixed in the 1.6.2 release.

**Comment by mblomdahl** [comment]
@sprattek Can you confirm that @carlba's assumption is correct? Should be fixed with #62. If so, please close this issue.

**Comment by sprattek** [comment]
@mblomdahl @carlba sorry guys for delay, yes it seems fixed, thank you.

**Comment by sprattek** [comment]
Hey guys, I've noticed that this issue still exists there when you try to drag circle across the popup. I've updated the [codepen example](https://codepen.io/anon/pen/vWxLXw) so you can easily check it out. Thanks.

**Comment by ghost** [comment]
@sprattek This is actually working by design. "Drag" is cancelled if you go outside the map canvas element, because we can't reliably track what you're doing outside the window or on external HTML elements (e.g. mouse-up). The kittens are actually on the map canvas; the popup is just a floating div somewhere. :)
